language: node_js
node_js:
  - "7"

cache:
  directories:
    - "node_modules"

install:
 - npm install -g codecov

script:
 - npm install
 - npm test

after_success:
# - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
 - codecov
