language: node_js
node_js:
  - "7"

cache:
  directories:
    - "node_modules"

before_install:
 - npm i -g npm@version-number

script:
 - npm install
 - npm run build

after_success:
 - bash <(curl -s https://codecov.io/bash)
